# fly.toml - Cấu hình Fly.io cho Telegram Bot Worker

app = 'crypto-crawl-bot'
primary_region = 'sin'

[build]

[processes]
  app = "python 2_crypto.py"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
